// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.9.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Platform platform({dynamic hint}) => RustLib.instance.api.platform(hint: hint);

bool rustReleaseMode({dynamic hint}) =>
    RustLib.instance.api.rustReleaseMode(hint: hint);

enum Platform {
  unknown,
  android,
  ios,
  windows,
  unix,
  macIntel,
  macApple,
  wasm,
}
