// This file initializes the dynamic library and connects it with the stub
// generated by flutter_rust_bridge_codegen.

import 'frb_generated.dart';

// Re-export the bridge so it is only necessary to import this file.
export 'frb_generated.dart';

// Re-export all of your API files here
export 'api/entry.dart';

// Before using any of the bindings, await this future.
// You can also customize initialization by changing the arguments passed to `init`.
// ignore: unnecessary_late
late final initialized = RustLib.init();
