name: CI
on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  web:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: wasm-pack,just,wasm-bindgen-cli
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: just build-web /flutter_rust_bridge_template/
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
