name: Issues Cleanup
on:
  schedule:
    - cron: '0 18 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  cleanup:
    name: Close Stale Issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5.1.0
        with:
          days-before-stale: 14
